; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+8 on Tue Mar 05 2024 06:46:39 GMT+0100 (Mitteleuropäische Normalzeit)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


