; bed.g
; called to level the bed
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.3+2 on Mon Apr 08 2024 17:15:16 GMT+0200 (Mitteleuropäische Sommerzeit)

G29 ; call mesh bed compensation
