; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.3+2 on Mon Apr 08 2024 17:15:16 GMT+0200 (Mitteleuropäische Sommerzeit)

G92 X0 ; set X=0
M118 L1 P0 S"Warning: X is NOT homed but its position has been set to 0."
