; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.3+2 on Mon Apr 08 2024 17:15:16 GMT+0200 (Mitteleuropäische Sommerzeit)

G92 Z0 ; set Z=0
M118 L1 P0 S"Warning: Z is NOT homed but its position has been set to 0."
