; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.3+2 on Mon Apr 08 2024 17:15:16 GMT+0200 (Mitteleuropäische Sommerzeit)

G92 Y0 ; set Y=0
M118 L1 P0 S"Warning: Y is NOT homed but its position has been set to 0."
