; homea.g
; called to home the A axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.3 on Tue Mar 05 2024 07:07:56 GMT+0100 (Mitteleuropäische Normalzeit)

G92 A0 ; set A=0
M118 L1 P0 S"Warning: A is NOT homed but its position has been set to 0."
