; homeb.g
; called to home the B axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.3 on Tue Mar 05 2024 07:07:56 GMT+0100 (Mitteleuropäische Normalzeit)

G92 B0 ; set B=0
M118 L1 P0 S"Warning: B is NOT homed but its position has been set to 0."
